config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get '/' => 'pages#homepage'

  get '/aboutus' => 'pages#aboutus'

  get '/partnerships' => 'pages#partnerships'

  get '/white-label' => 'pages#white-label'

  get '/seo' => 'pages#seo'

  get '/which-one' => 'pages#which-one'

  get 'web-apps' => 'pages#web-apps'

  get '/websites' => 'pages#websites'

  get '/portfolio-dbd' => 'pages#portfolio-dbd'

  get '/mobile-first' => 'pages#mobile-first'

  get '/process' => 'pages#process'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of  :title, :description, :body, :author, :imagelink

	def slug
    title.downcase.gsub(" ", "-")
  end

  def to_param
    "#{id}-#{slug}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




   private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :author, :body, :imagelink)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @articles = Article.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @article = Article.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to article_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :body, :author, :imagelink)
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :description, :body, :author, :imagelink)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :imagelink %><br>
    <%= f.text_field :imagelink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="full_page_photo no_photo">

</div>

<div class="main">
  <div class="container triangles-of-section">
               <div class="triangle-up-left"></div>
               <div class="square-left"></div>
               <div class="triangle-up-right"></div>
               <div class="square-right"></div>
          </div>
  <section>
     <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
             <h1>Editing Blog Post</h1>

								<%= render 'form' %>

								<%= link_to 'Show', @article %> |
								<%= link_to 'Back', articles_path %>


            </div>
        </div>
    </div>


  </section>
</div>

app/views/articles/index.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TLN8H3"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TLN8H3');</script>
<!-- End Google Tag Manager -->

<!-- Meta tags -->
<% set_meta_tags title: "Miami Tech Scene",
                 description: "Keep up with us What we Enjoy Slide to the right for more Articles ",
								 og: {
									 title: "Your Mobile-First Web Heroes",
									 type: 'website',
									 url: "http://www.deepbluedev.co/articles",
									 description:"Get in touch with Deep Blue Dev to discover how we can propel your development!",
									 image: "http://i.imgur.com/jzcej1u.png"
									 }%>

<section class="page-title style3" data-path="img/headers/header10.jpeg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="strong text-uppercase">What we Enjoy</h1>
        <ol class="breadcrumb hidden-xs">
          <li><a href="/"><i class="fa fa-home"></i></a></li>
          <li><a href="/articles">Blog</a></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="featured-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">

            <h1 class="strong">Keep up with us</h1>
            <div class="cbp cbp-slider-edge featured-slider">
              <% @articles.all.order('created_at DESC').each do |blog_post| %>
              <div class="cbp-item">
                <a href="articles/<%= blog_post.id %>" title="Read full post">
                  <div class="featured-post" data-path="<%= blog_post.imagelink %>" style="background: url(img/blog/large/1.jpg);">
                    <div class="post-content">
                      <p class="label label-warning post-category"></p>
                      <h3 class="post-title"><%= blog_post.title%></h3>
                    </div>
                    <div class="post-meta">
                      <span class="post-date"><%= blog_post.created_at %></span>
                    </div>
                  </div>
                </a>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-12"><h3>Slide to the right for more Articles <span> <i class="fa fa-arrow-right"></i></span></h3></div>

        </div>
      </div>
    </section>





              <%#= blog_post.description %>






<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67120211-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/articles/new.html.erb
<div class="full_page_photo no_photo">

</div>

<div class="main">
  <div class="container triangles-of-section">
               <div class="triangle-up-left"></div>
               <div class="square-left"></div>
               <div class="triangle-up-right"></div>
               <div class="square-right"></div>
          </div>
  <section>
     <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

								<h1>New Blog Post</h1>


								<%= render 'form' %>

								<%= link_to 'Back', articles_path %>


            </div>
        </div>
    </div>


  </section>
</div>

app/views/articles/show.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TLN8H3"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TLN8H3');</script>
<!-- End Google Tag Manager -->

<!-- Meta tags -->
<% set_meta_tags title: "#{@article.title}",
                 description: "#{@article.body.truncate_words(20)}",
								 og: {
									 title: "Your Mobile-First Web Heroes",
									 type: 'website',
									 url: "http://www.deepbluedev.co/articles/#{@article.id}",
									 description:"#{@article.body.truncate_words(20)}",
									 image: "http://i.imgur.com/jzcej1u.png"
									 }%>
<hr class="spacer-30">
<section class="section" id="scrollTo">
      <div class="container">
        <div class="row">
          <div class="col-md-9 col-sm-8">

            <!-- single post START -->
            <div class="single-post style1">

              <div class="thumb-wrapper">
                <!-- <div class="thumbs-carousel">
                    <img src="<%#= @article.imagelink %>" alt="Thumbnail">
                </div> -->
                <%= image_tag(@article.imagelink) %>
                <a id="blogtext" href="javascript:void(0);" class="post-author" data-toggle="tooltip" title="<%= @article.author %>">

              </div>


              <h2 class="h1 post-title"><%= @article.title %></h2>
              <div class="post-meta">
                <span class="post-category">Technology</span>
                <span class="post-date"><%= @article.created_at %></span>

              </div>
              <%#= @article.imagelink %>

              <h4><%=  @article.body %></h4>
              <%= link_to 'Back', articles_path, class: 'btn btn-primary' %>

            </div>
            <!-- single post END -->


            <!-- next/previous posts START -->
            <!-- <div class="row">
              <div class="col-md-6">
                <h4 class="next-prev-posts">
                  <small>Previous Post</small>
                  <a href="javascript:void(0);" title="Trends in technology are about to change">Trends in technology are about to change</a>
                </h4>
              </div>
              <div class="col-md-6">
                <h4 class="next-prev-posts text-right">
                  <small>Next Post</small>
                  <a href="javascript:void(0);" title="Initial wireframes of my first web design">Lorem ipsum dolor sitam consectetur adipiscing elit.</a>
                </h4>
              </div>
            </div> -->
            <!-- next/previous posts END -->

            <!-- author box START -->
           <!--  <section class="author-box">
              <h5 class="page-header">About Author</h5>
              <div class="media">
                <div class="media-left">
                  <a href="profile.html" title="Cole Martin">
                    <img src="img/authors/author3.jpg" class="media-object" alt="Cole Martin">
                  </a>
                  <a href="profile.html" class="btn btn-default profile-btn" data-toggle="tooltip" title="View author profile">View Profile</a>
                </div>
                <div class="media-body">

                  <h4 class="media-heading">Mr. Cole Martin </h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tristique mauris quis nisi elementum suscipit gerat. Integer luctus a nunc eu rhoncus. Integer mollis ante a consequat condimentum etiam etmi magna.</p>
                  <p class="small"><strong>Contributions:</strong> <a href="javascript:void(0);" title="All posts by Cole">456</a></p>
                  <div class="author-social" data-toggle="tooltip" data-original-title="Author's social profiles">
                    <i class="fa fa-share-alt"></i>
                    <ul class="social">
                      <li>
                        <a href="javascript:void(0);" title="facebook">
                          <i class="livicon" data-name="facebook" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="twitter">
                          <i class="livicon" data-name="twitter" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="linkedin">
                          <i class="livicon" data-name="linkedin" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="pinterest">
                          <i class="livicon" data-name="pinterest" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="dribbble">
                          <i class="livicon" data-name="dribbble" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="reddit">
                          <i class="livicon" data-name="reddit" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" title="skype">
                          <i class="livicon" data-name="skype" data-hovercolor="#333" data-size="18" data-onparent="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </section> -->
            <!-- author box END -->







        </div>
      </div>
    </section>






<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67120211-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" type="image/jpg" href="https://deepbluedev.slack.com/files/fe/F0ETP2LRH/deepblueicon.png">
	 <%= display_meta_tags %>
	<meta name="google-site-verification" content="WVVFC8iluh53KAEFE38wZayrpb-jLwZP_XSKc3PWJtI" />
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="google-site-verification" content="8ppL7u023VorNdHQ6XUxic0kx6vnjvclWwk5U4hRh-M" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta name="keywords" content="miami, miami web development, websites, seo, seo services, web development services, outsourcing web development, build a web app, build a website, website traffic, website analysis, web application, web app, website, developer, website developer, application developer">

	<meta name="description" content="Your mobile first Web heroes, Deep Blue Dev can handle all your web needs and presence. Websites, Web applications, Search engine and Mobile Optimization.">

	<meta name="author" content="Deep Blue Development">

	<script src="//load.sumome.com/" data-sumo-site-id="425993d7ef1da18ebeb676a3f7fcb3fdaabf65b1dc4bab215933f9e682853fde" async="async"></script>
</head>
<body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PF64ZJ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PF64ZJ');</script>
<!-- End Google Tag Manager -->

	<!-- preloader START -->
<div class="preloader">
	<div class="spinner-wrap">
		<div class="spinner spinner-wave">
			<div class="rect1"></div>
			<div class="rect2"></div>
			<div class="rect3"></div>
			<div class="rect4"></div>
			<div class="rect5"></div>
		</div>
	</div>
</div>
<!-- preloader END -->


<nav class="navbar navbar-custom transparent-nav navbar-fixed-top mega-menu" role="navigation">
	<div class="container">

		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><%= image_tag('http://i.imgur.com/jzcej1u.png') %></a>
		</div>



		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="fa fa-chevron-down"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to 'About', aboutus_path %></li>
						<li><a href="/portfolio-dbd" title="Portfolio">Porfolio</a></li>
						<li class="submenu left-dropdown">
							<a href="javascript:void(0);" title="Opportunities">Opportunities</a>
							<ul class="dropdown-menu">
								<li><a href="/white-label" title="White-Label Solutions">White-Label Solutions</a></li>
								<li><a href="/partnerships" title="Become a Partner">Become a Partner</a></li>
								<li><a href="http://www.indeed.com/viewjob?t=sales+administrator&jk=6c92c7a97b5ab551&_ga=1.73327251.1808495630.1441312763" title="Careers">Careers</a></li>
							</ul>
						</li>
						<li><a href="/articles" title="Blog">Blog</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="fa fa-chevron-down"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="/seo" title="Search Engine Optimization">Search Engine Optimization</a></li>
						<li class="submenu left-dropdown">
							<a href="javascript:void(0);" title="Development">Development</a>
							<ul class="dropdown-menu">
								<li><a href="/web-apps" title="Web Applications">Web Applications</a></li>
								<li><a href="/websites" title="Websites">Websites</a></li>
							</ul>
						</li>
						<li class="submenu left-dropdown">
							<a href="javascript:void(0);" title="Mobile-First Optimization">Mobile-First Optimization</a>
							<ul class="dropdown-menu">
								<li><a href="/mobile-first" title="Get Mobile Friendly">Get Mobile Friendly</a></li>
								<li><a href="https://www.google.com/webmasters/tools/mobile-friendly/" title="Mobile Friendly Test">Mobile Friendly Test</a></li>
							</ul>
						</li>

					</ul>
				</li>

				<li class="dropdown">
					<a class="btn btn-info btn-xs sq-corner" href="callto:8446333725">(844) 633-3725</a>
				</li>

			</ul>
		</div><!-- /.navbar-collapse -->

	</div><!-- /.container -->
</nav>
<!-- main navigation END -->


<%= yield %>

<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-sm-12">

				<h4 class="strong">About Deep Blue Dev</h4>
				<p>We are a Mobile-first Dev shop and Internet Marketing Firm. Bring your internet needs to us and let us build you a custom solution. Have an idea for the next big Start-up? Deep Blue can be your technical Co-founder.</p>
		<a title="Contact Us" data-toggle="modal" data-target="#gen_contact_modal" class="btn btn-default btn-icon contact-btn"><i class="livicon" data-name="mail" data-color="#fff" data-hovercolor="false" data-size="18"></i> Contact Us</a>

			</div>
		<div class="col-lg-2 col-sm-4 col-lg-offset-4">

				<h4 class="strong">Company</h4>
				<ul class="ft-list">
					<li><a href="/aboutus" title="Link title here">About Us</a></li>
					<li><a href="/partnerships" title="Link title here">Partners</a></li>
					<!-- Add process page -->
					<li><a href="#" title="Link title here">Our Process</a></li>
					<li><a href="http://www.indeed.com/viewjob?t=sales+administrator&jk=6c92c7a97b5ab551&_ga=1.73327251.1808495630.1441312763" title="Link title here">Careers</a></li>
				</ul>

		</div>
		<div class="col-lg-2 col-sm-4">

				<h4 class="strong">Services</h4>
				<ul class="ft-list">
					<li><a href="/seo" title="Link title here">Search Engine Optimization</a></li>
					<li><a href="/which-one" title="Link title here">Mobile-Friendly Optimization</a></li>
					<li><a href="/which-one" title="Link title here">Web Development &amp; Websites</a></li>
					<li><a href="/web-apps" title="Link title here">Custom Business Solutions</a></li>
				</ul>

		</div>


		</div>
		<hr>
		<div class="row">
			<div class="col-sm-8 hidden-xs">

				<ul class="list-inline">
					<li><a href="/portfolio-dbd" title="Link title here">Portfolio</a></li>
					<li><a href="/white-label" title="Link title here">White-Label</a></li>
					<li><a href="/articles" title="Link title here">Blog</a></li>
					<li><a href="/portfolio-dbd" title="Link title here">Clients</a></li>
				</ul>

			</div>
			<div class="col-sm-4">

				<div class="ft-social text-right">
					<a class="cst-btn-ten" href="https://plus.google.com/b/104744400389583009455/104744400389583009455/posts"><i class="fa fa-google-plus"></i><span>p</span></a>
					<a class="cst-btn-ten" href="https://www.linkedin.com/company/deep-blue-development?report%2Esuccess=KJ_KkFGTDCfMt-A7wV3Fn9Yvgwr02Kd6AZHGx4bQCDiP6-2rfP2oxyVoEQiPrcAQ7Bf"><i class="fa fa-linkedin"></i><span>in</span></a>
					<a class="cst-btn-ten" href="https://twitter.com/deepbluedev"><i class="fa fa-twitter"></i><span>t</span></a>
				</div>

			</div>
			<div class="col-lg-12 col-sm-6">

				<p class="copyright">© 2015 Deep Blue Development</p>

			</div>
		</div>

	</div>
</footer>

<!-- Modals -->
<!-- Modals -->
<!-- Modals -->
<!-- Modals -->
<!-- General Contact Modal -->
<div class="modal fade" id="gen_contact_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Get in Touch With us!</h4>
      </div>
      <div id="gen_contact_modal_body" class="modal-body">

			<!--[if lte IE 8]>
			<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
			<![endif]-->
			<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
			<script>
			  hbspt.forms.create({
			    css: '',
			    portalId: '1752173',
			    formId: 'ea2c6b25-ba1b-47b1-b51c-4b275b604de5'
			  });
			</script>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- /Gen Contact Modal -->




<!-- /Modals -->
<!-- /Modals -->
<!-- /Modals -->
<!-- /Modals -->
<!-- /Modals -->




<script type="text/javascript">
$(document).ready(function(){
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL;
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>

</body>
</html>